version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: authentication_db
    environment:
      POSTGRES_DB: Authentication
      POSTGRES_USER: Authentication
      POSTGRES_PASSWORD: Authentication
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Authentication -d Authentication"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: